# Generated by Django 4.1.3 on 2022-11-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.CharField(max_length=1000)),
                ('image_id', models.CharField(max_length=100, null=True)),
                ('image_short_id', models.CharField(max_length=100, null=True)),
                ('tags', models.CharField(max_length=1000, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
